name: Workflow lint

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check GitHub Actions workflows
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
